// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Shorturl struct {
	ID        int32          `json:"id"`
	Origin    sql.NullString `json:"origin"`
	Short     sql.NullString `json:"short"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
